var express = require('express');
var router = express.Router();
/* GET home page. */
router.post('/login', function (req, res) {
    console.log(req.body);
    res.json({
        "account": "admin",
        "menuDTOList": [{
            "level": 1,
            "name": "大屏展现",
            "no": "S",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "0",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 1,
            "name": "加钞规划",
            "no": "P",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "0",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 1,
            "name": "GIS分析",
            "no": "M",
            "note": null,
            "order": 2,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "0",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 1,
            "name": "多维分析",
            "no": "B",
            "note": null,
            "order": 3,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "0",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 1,
            "name": "统计报表",
            "no": "R",
            "note": null,
            "order": 4,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "0",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 1,
            "name": "明细查询",
            "no": "Q",
            "note": null,
            "order": 5,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "0",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 1,
            "name": "数据挖掘",
            "no": "L",
            "note": null,
            "order": 6,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "0",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 1,
            "name": "平台监控",
            "no": "K",
            "note": null,
            "order": 7,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "0",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 1,
            "name": "监控预警",
            "no": "J",
            "note": null,
            "order": 8,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "0",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 1,
            "name": "系统管理",
            "no": "F",
            "note": null,
            "order": 9,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "0",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 1,
            "name": "开发者模式",
            "no": "D",
            "note": null,
            "order": 10,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "0",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "加钞规划",
            "no": "P01",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "P",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "图表组件",
            "no": "D01",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "多维分析",
            "no": "B01",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "B",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "平台监控",
            "no": "K01",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "K",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "统计报表",
            "no": "R01",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "R",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "地理信息分析",
            "no": "M01",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "M",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "机构管理",
            "no": "F01",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "大数据监控",
            "no": "J01",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "J",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "预测",
            "no": "L01",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "L",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "明细查询",
            "no": "Q01",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "Q",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "多维分析",
            "no": "D02",
            "note": null,
            "order": 2,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "角色管理",
            "no": "F02",
            "note": null,
            "order": 2,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "用户管理",
            "no": "F03",
            "note": null,
            "order": 3,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "OLAP",
            "no": "D03",
            "note": null,
            "order": 3,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "明细查询模块开发",
            "no": "D04",
            "note": null,
            "order": 4,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "组件管理",
            "no": "F04",
            "note": null,
            "order": 4,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "定时任务管理",
            "no": "F05",
            "note": null,
            "order": 5,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "报表模板管理",
            "no": "D05",
            "note": null,
            "order": 5,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "明细查询",
            "no": "F06",
            "note": null,
            "order": 6,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "GIS信息开发",
            "no": "D06",
            "note": null,
            "order": 6,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 2,
            "name": "设备成本管理",
            "no": "F07",
            "note": null,
            "order": 7,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "角色信息",
            "no": "F0201",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F02",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "明细查询",
            "no": "Q0101",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "Q01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "GIS信息开发",
            "no": "D0601",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D06",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "区域配钞",
            "no": "P0601",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "P01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "执行特殊规则",
            "no": "P0501",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "P01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "加钞规划",
            "no": "P0101",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "P01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "图表组件开发",
            "no": "D0101",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "设备成本管理",
            "no": "F0701",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F07",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "定时任务管理",
            "no": "F0501",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F05",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "特殊日期配钞",
            "no": "P0701",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "P01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "明细查询模板开发",
            "no": "D0401",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D04",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "加钞任务",
            "no": "P0102",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "P01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "系统用户",
            "no": "F0301",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F03",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "统计报表",
            "no": "B0101",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "B01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "区域特殊日期配钞",
            "no": "P0801",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "P01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "HDFS监控",
            "no": "K0101",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "K01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "设备优先选择配置",
            "no": "P0201",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "P01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "多维分析模板开发",
            "no": "D0201",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D02",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "固定报表",
            "no": "R0101",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "R01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "ATM服务站运营分析",
            "no": "M0101",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "M01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "机构信息",
            "no": "F0101",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "报表模板管理",
            "no": "D0501",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D05",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "网点线路信息管理",
            "no": "P0301",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "P01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "业务实时监控",
            "no": "J0101",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "J01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "明细查询",
            "no": "F0601",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F06",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "预测ATM取款量",
            "no": "L0101",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "L01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "组件管理",
            "no": "F0401",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F04",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "特殊加钞规则管理",
            "no": "P0401",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "P01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "OLAP控管台",
            "no": "D0301",
            "note": null,
            "order": 1,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "D03",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "异常监控",
            "no": "J0102",
            "note": null,
            "order": 2,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "J01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "信用卡商铺推荐",
            "no": "L0102",
            "note": null,
            "order": 2,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "L01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "定时任务日志",
            "no": "F0502",
            "note": null,
            "order": 2,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F05",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "用户密码",
            "no": "F0302",
            "note": null,
            "order": 2,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "F03",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "即席查询",
            "no": "B0102",
            "note": null,
            "order": 2,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "B01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "MapReduce",
            "no": "K0102",
            "note": null,
            "order": 2,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "K01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "交互式报表",
            "no": "R0102",
            "note": null,
            "order": 2,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "R01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "HBase监控",
            "no": "K0103",
            "note": null,
            "order": 3,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "K01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "Spark监控",
            "no": "K0104",
            "note": "",
            "order": 4,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "K01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }, {
            "level": 3,
            "name": "基础监控",
            "no": "K0105",
            "note": null,
            "order": 5,
            "subMenu": [],
            "superMenu": {
                "level": null,
                "name": null,
                "no": "K01",
                "note": null,
                "order": null,
                "subMenu": [],
                "superMenu": null,
                "uRL": null
            },
            "uRL": null
        }],
        "name": "admin",
        "orgGrade": 1,
        "orgName": "总行",
        "orgNo": "0000",
        "retCode": "00",
        "retMsg": "登陆成功",
        "roleCatalog": 1,
        "usrDefView": "{\"cards\":[{\"id\":\"d45ed0f5-f2c9-49cb-8304-6a27db464320\",\"name\":\"法国红酒\",\"icon\":\"anticon-dot-chart\",\"desc\":\"是的风格\"},{},{\"id\":\"4512dbe9-1006-42f7-91de-c6b52d904243\",\"name\":\"洒水多\",\"icon\":\"anticon-dot-chart\",\"desc\":\"阿什顿发\"},{\"id\":\"57e47e72-7c1b-4da8-8d28-075f9cb32755\",\"name\":\"折线图\",\"icon\":\"anticon-dot-chart\",\"desc\":\"测试\"}],\"tabs\":[[{\"id\":\"4512dbe9-1006-42f7-91de-c6b52d904243\",\"name\":\"洒水多\",\"icon\":\"anticon-dot-chart\",\"desc\":\"阿什顿发\"},{\"id\":\"57e47e72-7c1b-4da8-8d28-075f9cb32755\",\"name\":\"折线图\",\"icon\":\"anticon-dot-chart\",\"desc\":\"测试\"}],[{\"id\":\"4512dbe9-1006-42f7-91de-c6b52d904243\",\"name\":\"洒水多\",\"icon\":\"anticon-dot-chart\",\"desc\":\"阿什顿发\"},{\"id\":\"57e47e72-7c1b-4da8-8d28-075f9cb32755\",\"name\":\"折线图\",\"icon\":\"anticon-dot-chart\",\"desc\":\"测试\"}]]}",
        "webToken": "C39173722F882A1A1E5D1E4AA65D50E4"
    });
});
module.exports = router;
